### ISSUE TITLE
Repo Renames

### ISSUE THREAD

**Issue by clux** [kube-rs/kube#1018]
For consistency with similar setups in the ecosystem, and consistency inside the org, I would like to propose the following two renames:

### 1. Repo rename: `kube-rs/kube-rs` -> `kube-rs/kube`

We do not need to highlight the -rs suffix twice (that feels more like the orgs job). The crate we are publishing is `kube`. This also looks cleaner and is more in line with how other org based setups name their primary repo (e.g. [tokio-rs/tokio](https://github.com/tokio-rs/tokio)).

### 2. Default branch rename: `master` -> `main`

To be in-line with the rest of the repos in the org that already have updated. Gotten used to it everywhere and liking the shorter name more than master. Now feels like a good time to do it. Can take this or leave it, but it's easy to do now.

Yay/Nay? @kube-rs/maintainers

**Comment by kazk** [comment]
:+1: for both

**Comment by teozkr** [comment]
:+1: on 1.

2 should obviously be done for a new repo, but it kinda sucks that it breaks existing git dependencies. Probably still worth doing on the balance.
