### ISSUE TITLE
client: Metadata-only API

### ISSUE THREAD

**Issue by olix0r** [kube-rs/kube#1027]
[client-go supports operations that only interact with resource metadata]( 
https://github.com/kubernetes/client-go/blob/be20b2bd91d8997dd6e42647be047973acb8cdee/metadata/metadata.go#L180-L306) via the [`PartialObjectMetadata` type](https://github.com/kubernetes/apimachinery/blob/7fb78ee962897d9de6bac4a8f0f1346eb1480ac4/pkg/apis/meta/v1/types.go#L1425-L1434). This can allow controllers to substantially reduce I/O and memory requirements when they don't actually need an object's spec or status.

We should extend the `Api` type with something like:

- `async fn get_metadata(name: &str) -> Result<ObjectMeta>`
- `async fn list_metadata(lp: &ListParams) -> Result<ObjectList<ObjectMeta>>`
- `async fn patch_metadata(name: &str, pp: &PatchParams, patch: &Patch<P>) -> Result<ObjectMeta>`
- `async fn watch_metadata(lp: &ListParams, version: &str) -> Result<impl Stream<Item = Result<WatchEvent<ObjectMeta>>>>`

These signatures may not be 100% correct--please update as needed to reflect the actual API semantics. 

Discussed in https://github.com/kube-rs/kube/discussions/1023

**Comment by mateiidavid** [comment]
Hey folks :) Has anyone started working on this? I'd like to take it up. I can at the very least start looking a little bit into the requirements, report back here, and get the ball rolling on a conversation around the changes necessary. Lmk :)

**Comment by clux** [comment]
Hey @mateiidavid ! We have not started looking at this yet, so if you have time to look at getting the base functionality of this working, then that would indeed be very helpful!

I expect this can follow the same flow as the rest of the request flow initially:

- base `Request` impls in (probably) `kube-core/src/request.rs` (with some special care to handle the extended accept header)
- `Api` impls in `kube-client/src/api` (maybe core_methods file)

and have some kind of base integration tests for __some__ type for at least get/list/patch, and some `Request` level unit tests in kube-core. But I have not dug too deep into this.

**Comment by mateiidavid** [comment]
Thanks @clux, that's a lot to get me going. Will try to give periodic updates :)
