### ISSUE TITLE
Incorrect imports of `schemars` type

### ISSUE THREAD

**Issue by ralpha** [kube-rs/kube#1049]
### Current and expected behavior

Compile error on mismatched types.
The hard coded import in [`schema.rs`](https://github.com/kube-rs/kube/blob/main/kube-core/src/schema.rs) file can change with feature flags.
This type changes with the `preserve_order` flag in `schemars`.

### Possible solution

This line:
https://github.com/kube-rs/kube/blob/b92dc5ba25b0ab91c979b0dfe5cb9306ba157def/kube-core/src/schema.rs#L5
Should be changed to:
```rust
use schemars::MapEntry as Entry;
```
or just `use schemars::MapEntry;` and change the `match` lower down in the code (line 104-114).

### Additional context

Transfer of issue from https://github.com/GREsau/okapi/issues/109

Relevant code in schemars https://github.com/GREsau/schemars/blob/5268080b014152912a910e3fe8524c4c876407de/schemars/src/lib.rs#L306-L309

### Environment

All

### Affected crates

kube-core

### Would you like to work on fixing this bug?

no

**Comment by ralpha** [comment]
This might also be a `good first issue`.

**Comment by teozkr** [comment]
Ouch, good catch.
