### ISSUE TITLE
control env passed to auth_exec

### ISSUE THREAD

**Issue by aviramha** [kube-rs/kube#1060]
### Would you like to work on this feature?

yes

### What problem are you trying to solve?

Thank you for maintaining such high quality and useful crate.
We're using it heavily in our project https://github.com/metalbear-co/mirrord. 
The way our software works, is that it loads itself to processes using `LD_PRELOAD`/`DYLD_INSERT_LIBRARIES` then uses kube-rs to communicate with the k8s api. 
We're having problems in scenarios where users have `auth exec` because then we get injected (due to env of host being passed) to the command to get credentials, and then we get recursively stuck.
We do have some solutions in place to workaround that, but we keep hitting new issues and we thought about doing a more clear approach where we can control the execution of `auth exec`, specifically, which env vars are passed and which are not.

### Describe the solution you'd like

We have a working version in our fork that we use:
https://github.com/metalbear-co/kube/pull/1
We add `drop_env` to `ExecConfig` which is a list of keys to remove from the command environment before executing.
This is a bit patchy, because this doesn't exist in `ExecConfig` model, but was a very quick solution.

More suggestions welcome and we'll be happy to implement it and send a PR so it will be part of the mainstream

### Describe alternatives you've considered

I was thinking about giving the ability to specify a trait for executing, then passing it.
```rs
pub trait AuthExec {
 fn auth_exec(auth: &AuthInfo) -> ..
}
```
but wasn't sure how to pass it and if it will be accepted.

### Target crate for feature

kube-client

**Comment by clux** [comment]
Hm, we probably wouldn't extend these structs because they are basically copies of the upstream [`ExecConfig`](https://github.com/kubernetes/client-go/blob/7697067af71046b18e03dbda04e01a5bb17f9809/tools/clientcmd/api/types.go#L193-L275) and we try to mirror the functionality of client-go for this to avoid drift.

The upstream struct has evolved since last we checked though. It does look like it allows you specify evar overrides, so this would allow you to set them to the empty string, which would probably avoid your LD_PRELOAD issue. A PR that adds such functionality (and whatever other new functionality from upstream ExecConfig) would be accepted.

**Comment by aviramha** [comment]
Thanks for the response. I assumed it would be the reason. Not sure about the new change - you can already set to empty strings..?

**Comment by clux** [comment]
Oh, :facepalm: We do actually already support passing on `ExecConfig::env`.

..but does that not work? Wouldn't setting LD_PRELOAD="" be equivalent to dropping it?

**Comment by aviramha** [comment]
> Oh, :facepalm: We do actually already support passing on `ExecConfig::env`.
> 
> 
> 
> ..but does that not work? Wouldn't setting LD_PRELOAD="" be equivalent to dropping it?

We have more env vars that might leak to be "" and we don't know how each binary interacts with existing env but empty string.

**Comment by clux** [comment]
hm, right. while this is what client-go also does, I can see that it's awkward. Maybe adding support for this would be OK. The serde-skip you have should make it safe, and we can add documentation about the divergence linking back to this bug.

We should raise an issue against client-go with the same issue though so there's a chance of the options harmonising down the line. i couldn't find any issue related to both [exec and env](https://github.com/kubernetes/client-go/issues?q=is%3Aissue+exec) there.

**Comment by aviramha** [comment]
Okay, created https://github.com/kubernetes/client-go/issues/1177
I'll send a PR soon here.

**Comment by teozkr** [comment]
After experimenting a bit, it looks like even bash's relatively common `FOO= do-stuff` only sets `FOO=""`... :/
