### ISSUE TITLE
exec sh (shell) with tty not processing escape chars

### ISSUE THREAD

**Issue by Masber** [kube-rs/kube#1063]
#### Current behaviour

I have a code like this

```rust
pub async fn connect_to_console() -> Result<(), Box<dyn Error>> {

    let client = get_k8s_client_programmatically().await?;

    let pods_api: Api<Pod> = Api::namespaced(client, "services");

    let console_pod_name = "test";

    let command = vec!["bash"];

    let mut attached = pods_api.exec(
        &console_pod_name, 
        command,
        &AttachParams::default()
            .container("console-node")
            .stdin(true)
            .stdout(true)
            .stderr(false)
            .tty(true)
    ).await?;

    let mut user_input;
    let stdin = std::io::stdin();
    
    let mut stdin_writer = attached.stdin().unwrap();
    let mut stdout_stream = tokio_util::io::ReaderStream::new(attached.stdout().unwrap());

    let mut next_stdout;
    let mut stdout;

    user_input = String::new();
    
    let rt = Runtime::new().unwrap();
    rt.spawn(async move {
        loop {
            stdin.read_line(&mut user_input).unwrap();
            stdin_writer.write_all(format!("{}", user_input).as_bytes()).await.unwrap();
        }
    }); 

    loop {
        // Read command output
        next_stdout = stdout_stream.next().await;
        stdout = String::from_utf8(next_stdout.unwrap()?.to_vec()).unwrap();
        print!("{}", stdout);
        std::io::stdout().flush().unwrap();
    }
}
```

I can connect to the container 

```
nobody@cray-console-node-2:/> ps
    PID TTY          TIME CMD
 385929 pts/470  00:00:00 bash
 385953 pts/470  00:00:00 ps
```

However, when I press the up arrow key, I don't see the last command used but instead the command prints `^[[A`

#### Expected behaviour

when I run `kubectl exec -it ... -- bash` I can open an interactive session in bash and use the arrow keys to navigate through the shell history

### Additional context

In addition, when I press Ctrl+C my application exists, when I do that in a shell, it just prints `^C` but it does not exit kubectl. My impression is that my app is still connected to the pty slave 

### Environment

$ kubectl version --short
Client Version: v1.22.1
Server Version: v1.20.13

### Configuration and features

```toml
kube = { version = "0.74.0", features = ["runtime", "derive", "native-tls", "ws"] }
k8s-openapi = { version = "0.15.0", features = ["v1_24"] }
```

**Comment by kazk** [comment]
I believe this is out of scope of `kube` as a library. You can use crates like `crossterm` in your application to handle them. 

I haven't tested, but #983 includes a working example.

**Comment by clux** [comment]
Yeah, deferring to `crossterm` here should be the way to go. The above PR is very nicely plugging into `crossterm` in an example to do this, so going to close this when that gets merged (because while full handling of escape chars is out of scope for us, we do need to handle terminal size).
