### ISSUE TITLE
Parsing of kubeconfig is more strict than client-go

### ISSUE THREAD

**Issue by goenning** [kube-rs/kube#1076]
### Current and expected behavior

I noticed that `Kubeconfig::read()` is a bit more strict than client-go's when parsing the kubeconfig. For example:

In client-go, it's possible to have a context without a cluster or user. It won't actually work if you try to use that context, but it doesn't fail to parse it, meaning that users can use the other contexts that have all the required fields.

These are the differences I found:
- the `contexts.context` is optional in client-go, mandatory in kube-rs.
- the `contexts.context.name` is optional in client-go, mandatory in kube-rs.
- the `contexts.context.user` is optional in client-go, mandatory in kube-rs.
- the `users.user.auth-provider.config` is optional in client-go, mandatory in kube-rs.
- the `users.user.auth-provider.config` can be set to empty, `~` or null in client-go, but not in kube-rs
- there might be more though

### Possible solution

Relax the parsing of kubeconfig to match client-go as much as possible. To avoid further breaking changes, ideally if those fields are missing on kubeconfig, kube-rs would default it to empty strings / empty hash maps.

### Environment

Client Version: v1.25.3
Kustomize Version: v4.5.7
Server Version: v1.22.8
WARNING: version difference between client (1.25) and server (1.22) exceeds the supported minor version skew of +/-1

### Configuration and features

```toml
kube = { version = "0.76.0", features = ["client", "runtime", "ws", "gzip"]  }
k8s-openapi = { version = "0.16.0", features = ["v1_24"] }
```

### Affected crates

kube-client

### Would you like to work on fixing this bug?

yes

**Comment by clux** [comment]
I think that makes sense. We did add `Kubeconfig::default` to give out an empty config (which kubectl happily parses). 

Not quite sure where we make all of that stuff there mandatory, but I see at least some missing `#[serde(default)]` annotations on maps. Feel free to do a PR on this!

NB: There are possibly some finer points here about what "should consider parseable" and what we "should consider valid". If we are going to use it internally, we probably need it to be usable, but if we are just going to ::merge it, then we should definitely be as flexible as client-go.
