### ISSUE TITLE
Panic when using `watcher` with a resource that does not expose a `resourceVersion`

### ISSUE THREAD

**Issue by umanwizard** [kube-rs/kube#1092]
### Current and expected behavior

See title. The offending line is [here](https://github.com/kube-rs/kube/blob/468bb81/kube-runtime/src/watcher.rs#L143).

### Additional context

metrics-server apparently creates PodMetrics resources without this field, and my code panics when trying to watch them.

### Environment

```
Client Version: v1.22.10
Server Version: v1.23.4
```

```
FROM ubuntu:jammy-20221101
```

### Affected crates

kube-runtime

**Comment by teozkr** [comment]
I believe metrics-server is using an [extension API](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/apiserver-aggregation/), so I'm not sure they support watches at all. That said, we should definitely at least have clearer error messages for this, and avoid panicking...

**Comment by goenning** [comment]
I've hit this wall too, watch is not supported: https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/1013-metrics-watch-api

Polling is the only alternative AFAIK

**Comment by clux** [comment]
In that case should probably extend `watcher::Error` here with a `NoMetadata` error variant and bubble that up from the offending line above.

**Comment by clux** [comment]
Quick PR in #1101 to turn the unwrap into an error. This will cause a repeating error when watch is not supported though, but hopefully it's more informative and a developer can catch/notice this earlier and be less confused about it than if it was an unwrap.

**Comment by teozkr** [comment]
We may also want to add a `poll_watcher` at some point to cope with these cases...
