### ISSUE TITLE
Certificate validation fails on rancher using openssl

### ISSUE THREAD

**Issue by clux** [kube-rs/kube#1106]
### Current and expected behavior

Using default openssl stack and connecting to a rancher cluster yields an obscure openssl certificate error that goes away when setting `accept_invalid_certs`. This error does not present itself with rustls.

Error:
```
2022-12-13T15:21:05.413658Z ERROR kube_client::client::builder: failed with error error trying to connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1921:: unable to get local issuer certificate
Error: HyperError: error trying to connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1921:: unable to get local issuer certificate

Caused by:
    0: error trying to connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1921:: unable to get local issuer certificate
    1: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1921:: unable to get local issuer certificate
    2: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1921:
    3: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1921:
```

kubeconfig style:
```yaml
apiVersion: v1
kind: Config
clusters:
- cluster:
    server: https://rancher.HOSTNAME/k8s/clusters/c-8b68c
  name: rancher
- cluster:
    certificate-authority-data: BASE64=
    server: https://k8s-development-euw1.HOSTNAME:6443
  name: rancher-fqdn
contexts:
- context:
    cluster: rancher
    namespace: default
    user: rancher
  name: rancher
- context:
    cluster: rancher-fqdn
    user: rancher
  name: rancher-fqdn
current-context: rancher
users:
- name: rancher
  user:
    token: kubeconfig-u-XXXXXX.ZZZZZ:BIGSTRING
preferences: {}
```

### Environment

Cluster at 1.22. Works with kubectl, and works with rustls (using 0.77).
Backtracking kube versions makes it seem like this has never worked for us (tested ~3 releases).

### Affected crates

kube-client

**Comment by clux** [comment]
hm.. actually, i wonder if this is a me problem on a mac... i don't remember this cluster being problematic before on linux.

**Comment by goenning** [comment]
Have you enabled the censored feature on OpenSSL? Because I vaguely remember seeing that too, and the fix was to use `init_ssl_cert_env_vars` from the openssl_probe.

There is a note here: https://docs.rs/openssl/latest/openssl/

**Comment by clux** [comment]
hm, this is just from running `RUST_LOG=info cargo run --example kubectl -- get pods` inside the examples directory, so it's non-vendored ssl by default. Tried the following combinations (that all resulted in the same result):

- vendored openssl change in kube-client/Cargo.toml
- vendored openssl + openssl probe call in kubectl.rs main
- default openssl
- default openssl + openssl probe call in kubectl.rs main
- prefixing explicit brew `openssl@1.1 path` via `OPENSSL_DIR=/opt/homebrew/Cellar/openssl@1.1/1.1.1s/` before cargo run
- `OPENSSL_DIR` set with and without openssl_probe

i think it might be something else

**Comment by clux** [comment]
Well, I regenerated the kubeconfigs from rancher and re-installed the certs for it with `sudo security add trusted-cert` and the problem went away. It was something weird with my setup with possibly outdated certs. Weird that it worked with kubectl and not my setup, but don't want to spend more time in this rabbit hole.
