### ISSUE TITLE
[v0.77] shell exec is closed when TerminalSizeSender is dropped

### ISSUE THREAD

**Issue by erebe** [kube-rs/kube#1110]
### Current and expected behavior

Since version 0.77 due to commit, https://github.com/kube-rs/kube/commit/d574fbc0e9637a50f60deaaf03f8226d5bb22102
when doing a shell exec, if the terminalSizeSender of the attached process is dropped, the connection to the remote process/message loop is dropped/exited due to line https://github.com/kube-rs/kube/blob/main/kube-client/src/api/remote_command.rs#L328

Before version 0.77, one was able to take out only stdin and stdout from the AttachedProcess (and thus to drop it afterward) without the connexion with remote process exiting.

As example:
Doing this on version < 0.77 was ok
```rust
    let mut attached = pods.exec(pod_name, command, &ap).await?;
    let stdout = attached.stdout();
    let stdin = attached.stdin();
//    std::mem::forget(attached);

    return Ok((stdout.unwrap(), stdin.unwrap()))
```

since version 0.77, when attached is dropped, so is TerminalSizeSender, which endup triggering the exit of the message loop
uncommenting the `std::mem::forget(attached)` of the previous snippet make the code works

My expected behavior would be to avoid exiting the message loop even if the TerminalSizeSender is dropped, as one may not need it.

### Possible solution

```diff
diff --git a/kube-client/src/api/remote_command.rs b/kube-client/src/api/remote_command.rs
index 96b93ac..2c925df 100644
--- a/kube-client/src/api/remote_command.rs
+++ b/kube-client/src/api/remote_command.rs
@@ -255,7 +255,7 @@ where
     let (mut server_send, raw_server_recv) = stream.split();
     // Work with filtered messages to reduce noise.
     let mut server_recv = raw_server_recv.filter_map(filter_message).boxed();
-    let have_terminal_size_rx = terminal_size_rx.is_some();
+    let mut have_terminal_size_rx = terminal_size_rx.is_some();

     loop {
         let terminal_size_next = async {
@@ -325,7 +325,7 @@ where
                         server_send.send(ws::Message::Binary(vec)).await.map_err(Error::SendTerminalSize)?;
                     },
                     None => {
-                        break
+                        have_terminal_size_rx = false;
                     }
                 }
             },
```

### Additional context

I can make a patch if the solution is ok to you

### Environment

❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"archive", BuildDate:"2021-11-18T21:20:32Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.15-eks-fb459a0", GitCommit:"be82fa628e60d024275efaa239bfe53a9119c2d9", GitTreeState:"clean", BuildDate:"2022-10-24T20:33:23Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

### Affected crates

kube-client

### Would you like to work on fixing this bug?

yes

**Comment by clux** [comment]
Thanks for the report!

Yeah, I think your suggestion makes sense here. Users might not always care about this.
A PR here would be much appreciated!

**Comment by erebe** [comment]
Opened a PR for it https://github.com/kube-rs/kube/pull/1112
