### ISSUE TITLE
unresolved import `kube::api::AttachParams` no `AttachParams` in `api`

### ISSUE THREAD

**Issue by shenshouer** [kube-rs/kube#1159]
### Current and expected behavior

Current behavior:
When I run the example `pod_shell.rs` https://github.com/kube-rs/kube/blob/main/examples/pod_shell.rs, compile error: unresolved import `kube::api::AttachParams` no `AttachParams` in `api`

The Cargo.toml:

```
[package]
name = "example-ssh"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
async-trait = "0.1.64"
dotenv = "0.15.0"
env_logger = "0.10.0"
futures = "0.3.26"
ldap3 = "0.11.1"
russh = "0.36.1"
russh-keys = "0.24.1"
tokio = { version = "1.26.0", features = ["full"]}
kube = { version = "0.80.0", features = ["client", "runtime", "derive"] }
k8s-openapi = { version = "0.17.0", features = ["v1_26"] }
tracing = "0.1.37"
serde_json = "1.0.93"
tracing-subscriber = "0.3.16"
serde = { version = "1.0.152", features = ["derive"] }
```

### Environment

% kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.25.4
Kustomize Version: v4.5.7
Server Version: v1.25.4

### Would you like to work on fixing this bug?

None

**Comment by clux** [comment]
The example works in `main` using just `cargo run --example pod_shell`.

It looks like your `toml` is missing the `ws` feature from `kube`.

**Comment by shenshouer** [comment]
Yes, If i add feature ws, it worked.

```
kube = { version = "0.80.0", features = ["client", "runtime", "derive", "ws"] }
```

**Comment by frapa** [comment]
I stumbled on the same error. The cause for this is that [the API docs](https://docs.rs/kube/latest/kube/api/struct.AttachParams.html) list it as requiring `client` not `ws`.

**Comment by clux** [comment]
Thanks this is a documentation issue on our end. Have raised this separately in #1242
