### ISSUE TITLE
Missing ws → tokio/macros feature dependency

### ISSUE THREAD

**Issue by jcfj** [kube-rs/kube#1168]
### Current and expected behavior

```
error[E0432]: unresolved import `tokio::select`
  --> /home/julius/.cargo/git/checkouts/kube-ea31f9bf5a02ffbe/2e5e4de/kube-client/src/api/remote_command.rs:13:5
   |
13 |     select,
   |     ^^^^^^ no `select` in the root
```

### Possible solution

```toml
ws = ["client", "tokio-tungstenite", "rand", "kube-core/ws", "tokio/macros"]
```

### Configuration and features

```toml
k8s-openapi = { version = "0.17.0", features = ["v1_26"] }
kube-client = { version = "0.80.0", features = ["ws"] }
```

### Affected crates

kube-client

### Would you like to work on fixing this bug?

So trivial that the overhead of making a PR and getting it approved is somewhat ridiculous.

**Comment by clux** [comment]
Thanks for the issue! Guess the three feature combinations tests we have for of (all, none, default) misses the default+ws case :/

> overhead of making a PR

hah. fair. I can include a fix for this for the next version in one of the smaller fixup prs.
