### ISSUE TITLE
AdmissionReview missing apiVersion and Kind

### ISSUE THREAD

**Issue by foosinn** [kube-rs/kube#1172]
### Current and expected behavior

When writing an admission controller with axum `apiVersion` and `kind` seem to be missing.

```rust
use kube::core::admission::{AdmissionRequest, AdmissionResponse, AdmissionReview};
use kube::core::DynamicObject;
use serde_json::json;

pub(crate) async fn mutate_secret(
    Json(payload): Json<AdmissionReview<DynamicObject>>,
) -> impl IntoResponse {
    println!("{}", json!(payload));
    let req: AdmissionRequest<DynamicObject> = payload.request.unwrap();
    let resp = AdmissionResponse::from(&req);

    let reviewed: AdmissionReview<_> = resp.into_review();
    println!("{}", json!(reviewed));
    Json(reviewed)
}
```

first output:

```json
{"apiVersion":"admission.k8s.io/v1","kind":"AdmissionReview","request":{"uid":"c3cf3e7d-137a-46ed-aec8-2c60d42eae8f","kind":{"group":"","version":"v1","kind":"Secret"},"resource":{"group":"","version":"v1","resource":"secrets","api_version":""},"subResource":null,"requestKind":{"group":"","version":"v1","kind":"Secret"},"requestResource":{"group":"","version":"v1","resource":"secrets","api_version":""},"requestSubResource":null,"name":"test","namespace":"default","operation":"CREATE","userInfo":{"groups":["system:masters","system:authenticated"],"username":"kubernetes-admin"},"object":{"apiVersion":"v1","kind":"Secret","metadata":{"managedFields":[{"apiVersion":"v1","fieldsType":"FieldsV1","fieldsV1":{"f:data":{".":{},"f:key1":{}},"f:type":{}},"manager":"kubectl-create","operation":"Update","time":"2023-03-29T23:05:17Z"}],"name":"test","namespace":"default"},"data":{"key1":"c3VwZXJzZWNyZXQ="},"type":"Opaque"},"oldObject":null,"dryRun":false,"options":{"kind":"CreateOptions","apiVersion":"meta.k8s.io/v1","fieldManager":"kubectl-create","fieldValidation":"Strict"}}}
```

second output:

```
{"apiVersion":"","kind":"","response":{"uid":"c3cf3e7d-137a-46ed-aec8-2c60d42eae8f","allowed":true,"status":{}}}
```

### Possible solution

copy `apiVersion` and `kind` from the incoming AdmissionReview

### Environment

Client Version: v1.26.3
Kustomize Version: v4.5.7
Server Version: v1.25.3

### Configuration and features

```
k8s-openapi = { version = "0.17.0", features = ["v1_26"] }
kube = { version = "0.80.0", features = ["runtime", "derive", "admission"] }
```

### Would you like to work on fixing this bug?

maybe

**Comment by foosinn** [comment]
This was a user error.

```diff
-let req: AdmissionRequest<DynamicObject> = payload.request.unwrap();
+let req: AdmissionRequest<DynamicObject> = payload.try_into().unwrap();

```

**Comment by eliphatfs** [comment]
i also hit this today, the documentation and code is disorganized, the typing is awkward with mututally exclusive Option<> everywhere where enum should be used, if users shouldn't use .request you should make it private and clearly advise in documentation that we should use try_into

**Comment by SOF3** [comment]
That's just generated from the K8s OpenAPI. This is more like an upstream problem, which is caused by the OpenAPI spec being generated from Go, which does not offer enums in the first place.

**Comment by eliphatfs** [comment]
Thank you for your reply. My point is that "when you are in rome, you should do what the romans do". When we are creating a rust library, we should try to translate these dumb go apis into rustic structures.

**Comment by SOF3** [comment]
Can't speak on behalf of maintainers, but porting all upstream type definitions to idiomatic Rust involves a large amount of manual workload. Maybe that's better done as a separate library?

**Comment by clux** [comment]
you all have good points here tbf.

1. i like the idea of making parts of it private and forcing a less error prone path.
2. this is a result of upstream code BUT it's [not part of the k8s-openapi](https://docs.rs/k8s-openapi/latest/k8s_openapi/?search=AdmissionReview) library

so there is technically some room here to create a tagged enum that serializes to what exists in go in a way that makes it less error prone.

but on the other hand

1. it would also be a breaking change
2. less and less people are writing admission controllers (with the advent of admission policies)
3. the struct is also bundled by [k8s-pb](https://docs.rs/k8s-pb/latest/k8s_pb/api/admission/v1/struct.AdmissionReview.html) so if we ever get around to integrating it it could make it awkward to migrate from this one in kube to the upstream variant

so i'm leaning towards not doing anything for it atm.
