### ISSUE TITLE
Add `GetParams` to mirror `GetOptional`

### ISSUE THREAD

**Issue by clux** [kube-rs/kube#1174]
### What problem are you trying to solve?

Allow querying `Api::get` with `Any`, `NotOlderThan` and `MostRecent` semantics

https://kubernetes.io/docs/reference/using-api/api-concepts/#semantics-for-get-and-list
https://pkg.go.dev/k8s.io/apimachinery/pkg/apis/meta/v1#GetOptions

Stashing this in an issue as we are waiting for #1171 first.

### Describe the solution you'd like

Something similar to what was recently added to `ListParams`, but we cannot use the `VersionMatch` enum here as that is not a query parameter for get calls.

```rust
/// Common query parameters used in get calls
#[derive(Clone, Debug, Default)]
pub struct GetParams {
    /// An explicit resource version with implicit version match strategies
    ///
    /// Default unset gives the most recent
    /// "0" gives the less consistent but-cheaper "Any", and an explicit value is like `VersionMatch::NotOlderThan`.
    /// See <https://kubernetes.io/docs/reference/using-api/api-concepts/#resource-versions> for details.
    pub resource_version: Option<String>,
}
```

and then possibly implement some helpers to make the new semantics more easy to setup:

```rust
impl GetParams {
    pub fn at(resource_version: &str) -> Self {
        Self { resource_version: Some(resource_version.into()) } 
    }
    pub fn any() -> Self {
        Self::at("0")
    }
}
```

this can then be added to `Request::get`:

```rust
    pub fn get(&self, name: &str, gp: &GetParams) -> Result<http::Request<Vec<u8>>, Error> {
        let target = format!("{}/{}", self.url_path, name);
        let mut qp = form_urlencoded::Serializer::new(target);
        if let Some(rv) = &gp.resource_version {
            qp.append_pair("resourceVersion", rv.as_str());
        }
        let urlstr = qp.finish();
        let req = http::Request::get(urlstr);
        req.body(vec![]).map_err(Error::BuildRequest)
    }
```

### `Api` interface

We already have `Api::get` without `GetParams`, and if that was the only interface it'd be easy to either add to that, or add another `get` variant that takes the new params. However we also have `Api::get_opt` and `Api::entry`. So not quite sure what to do about those. Don't really want to expose variant methods for all those, so it's probably better to change the signatures of these 3.

### Documentation, Adoption, Migration Strategy

Release highlight if doing breaking change.

### Target crate for feature

kube-core, kube-client

**Comment by nabokihms** [comment]
Honestly, thought about adding this next to list options 😅

**Comment by mateiidavid** [comment]
Thanks for a super thorough description and suggestion :) I can take this.
