### ISSUE TITLE
Allow users to exclude `managedFields` from the `Controller` cache

### ISSUE THREAD

**Issue by nightkr** [kube-rs/kube#1210]
### Would you like to work on this feature?

None

### What problem are you trying to solve?

`managedFields` quickly gets huge, sometimes overwhelming the size of the actual objects (in my test cluster of 10k pods, `managedFields` takes up around half of the cache's memory).

### Describe the solution you'd like

Controller could take a preprocessing function, making the pipeline `watcher -> preprocess -> reflector -> scheduler -> executor -> scheduler`.

### Describe alternatives you've considered

We could also take a specific flag for stripping `managedFields`, since it is pretty unique in how large and useless it is (for clients! it is serving a very helpful purpose for the API server, but that isn't helped by the clients keeping it around too).

### Target crate for feature

kube-runtime

**Comment by clux** [comment]
I believe this is actually possible using the `unstable-streams` feature and it's partially shown in the [pod_reflector](https://github.com/kube-rs/kube/blob/e01187e13ba364ccecec452e023316a62fb13e04/examples/pod_reflector.rs#L31-L40) example which can be adapted with controllers:

```rust
    let (reader, writer) = reflector::store();
    let stream = watcher(api, watcher::Config::default()).map_ok(|ev| {
        ev.modify(|pod| {
            // memory optimization for our store - we don't care about fields/annotations/status
            pod.managed_fields_mut().clear();
        })
    });
    let rf = reflector(writer, stream).applied_objects();
    Controller::for_stream(stream, reader)
```

**Comment by nightkr** [comment]
Yeah, it should be. But it would be nice if we could find a way to cover it for the "friendly" `Controller::new` API too.

**Comment by clux** [comment]
Maybe, but this quickly becomes as complicated as the thing it wants to encapsulate. You have pre-processing (ev.modify), you have post-processing (predicatefilter), maybe streamsubscribe or whatever things we end up putting in `WatchStreamExt` which is hard to provide nice signature for.

There is also the question of what inputs do you apply the pre/post processing to. Just main stream? Ok, but then the same interface lack persists for people needing to watch owned/watched streams, and they need to drop down to the streams api anyway.

Swapping between `Controller::new` and `Controller::for_streams` is generally 3 lines in the default case:

```diff
+    let (reader, writer) = reflector::store();
+    let stream = watcher(api, watcher::Config::default()).backoff(...);
+    let rf = reflector(writer, stream).applied_objects();
+    Controller::for_stream(stream, reader)
-    Controller::new(api, watcher::Config::default()
```

(that's also ignoring the extra awkwardness of extracting `Controller::store` with `Controller::new` when you have to halt the builder chain.)

The main benefit of going through the "easy-mode" `Controller` over "hard-mode" `applier` is the merging of the streams with triggers/mappers/selectors (peripheral concepts to most devs) and presenting a semantic api for that, and `unstable-streams` interface preserves this.

(This definitely needs some docs on kube.rs, but have been holding off on that a bit to see how the unstable interface does.)

**Comment by nightkr** [comment]
We don't currently maintain a store for child watches anyway, so that shouldn't change too much.

**Comment by clux** [comment]
Added a thing about how to do this on kube.rs.

In particular, it shows how do do pruning pre-reflector: https://kube.rs/controllers/optimization/#pruning-fields
which you can take advantage of by in a `Controller` using the streams api (though still unstable): https://kube.rs/controllers/streams/#main-stream
