### ISSUE TITLE
Add a `WatchStreamExt::modify` shortcut

### ISSUE THREAD

**Issue by clux** [kube-rs/kube#1245]
## Would you like to work on this feature?

no

### What problem are you trying to solve?

Minor ergonomics improvement for the streams api. Currently stream modification requires:

```rust
let stream = watcher(api, watcher::Config::default()).map_ok(|ev| {
    ev.modify(|pod| {
        pod.managed_fields_mut().clear();
        pod.annotations_mut().clear();
        pod.status = None;
    })
});
```

we could shortcut that ever so slightly:

```rust
let stream = watcher(api, watcher::Config::default()).modify(|pod| {
    pod.managed_fields_mut().clear();
    pod.annotations_mut().clear();
    pod.status = None;
});
```

### Describe the solution you'd like

A new `WatchStreamExt::modify` that chains [`TryStreamExt::map_ok`](https://docs.rs/futures/latest/futures/stream/trait.TryStreamExt.html#method.map_ok) with [`watcher::Event::modify`](https://docs.rs/kube/latest/kube/runtime/watcher/enum.Event.html#method.modify)

Can be verified in [examples/pod_reflector.rs](https://github.com/kube-rs/kube/blob/main/examples/pod_reflector.rs#L31-L42).

### Describe alternatives you've considered

writing out the full thing, not a big deal, but a nice user facing api simplification when using the streams api.

### Documentation, Adoption, Migration Strategy

additive change, put it in the docs and the example.

### Target crate for feature

kube-runtime

**Comment by nightkr** [comment]
Yeah, nested maps tend to feel pretty awkward, especially when this is something that we want to encourage.
