### ISSUE TITLE
Allow setting controller `concurrency`

### ISSUE THREAD

**Issue by clux** [kube-rs/kube#1248]
### Would you like to work on this feature?

no

### What problem are you trying to solve?

I would like to control how many reconciliations occur at bootup without managing locks/semaphores.

~~Currently there is only [a constant set to 100](https://github.com/kube-rs/kube/blob/db585dd6de4690d04787b2b494553ef20818f150/kube-runtime/src/controller/mod.rs#L236) that serves our effective limit which [relies on channel sending blocking when its capacity is full](https://docs.rs/tokio/latest/tokio/sync/mpsc/struct.Sender.html#method.send) to limit throughput.~~ EDIT: This was wrong. We are just running with unbounded concurrency atm.

I would like to be able to to set concurrency somehow so that the workload of the controller is a little more linear. Currently, I frequently see reconciliation rates like this:
<img width="683" alt="Screenshot 2023-06-29 at 20 14 17" src="https://github.com/kube-rs/kube/assets/134092/480b4790-5a68-42b7-a0b0-842fb3e9386a">

Go comparisons: 
- [flux kustomize-controller allows customizing this](https://fluxcd.io/flux/components/kustomize/options/#flags)
- it basically just sets [MaxConcurrentReconciles](https://github.com/kubernetes-sigs/controller-runtime/blob/87487d3539d7ae1abf2857f2c8623637eb25266e/pkg/controller/controller.go#L38-L40) in controller-runtime

Have found that type of control very helpful there, because it makes the performance much more predictable, and you can also work out a good target concurrency by looking at your number of reconciled items, average reconcile times, requeue frequency (`num_items*avg_reconcile_duration/avg_requeue_delay`).

### Describe the solution you'd like

Would like to pass a value from `Controller::concurrency(self, u16)` that must propagate to the `applier` on `Controller::run` (probably in a some config struct in a similar manner to #1247).

There are some [backpressure tests](https://github.com/kube-rs/kube/blob/db585dd6de4690d04787b2b494553ef20818f150/kube-runtime/src/controller/mod.rs#L1289-L1293), which are helpful, but only affects the intermediate channel. The `Runner` is probably one of the places we can set this. See follow-up comments.

### Describe alternatives you've considered

There are basically two workarounds here:
#### 1. Reconciler Semaphore
Natalie has suggested a manual workaround for this in: https://github.com/kube-rs/website/pull/35#issuecomment-1606912628 - but was hoping something a little easier long term (particularly if we want to pass other parameters anyway).

#### 2. Duration Jitter
Rather than using a fixed requeue `Duration` from the reconciler, we instead add some jitter so that the reconciliations eventually stagger. Might improve things in the long run, but not in the beginning.

###  Documentation, Adoption, Migration Strategy

same as #1247

### Target crate for feature

kube-runtime

**Comment by nightkr** [comment]
FWIW, `APPLIER_REQUEUE_BUF_LIMIT` doesn't do what you want it to, either. It only governs the input buffer to the scheduler. This queue only contains objects that have just _finished_ reconciling and are about to be rescheduled. You should see roughly the same graph if you set it to 1.

**Comment by clux** [comment]
Oh, damn.

So we would have to put a semaphore into the `Runner` accomplish this then, probably?

**Comment by nightkr** [comment]
In short, yeah. I still think a semaphore around the limited resource itself (or some other form of rate limiting) would make it easier to understand the _why_, though.

**Comment by Dav1dde** [comment]
Assuming everything goes through a stream, [`StreamExt::buffer_unordered`](https://docs.rs/futures/latest/futures/prelude/stream/trait.StreamExt.html#method.buffer_unordered) may work. I'll see if I can take a look the next few days, I got some free time.

**Comment by aryan9600** [comment]
I might be going on the wrong path here, but can't we reuse the `pending` set that the scheduler has for this? Atm, it is used to make sure we don't run the reconcile loop for the same object simultaneously, but i _think_ we can also use it to store requests that can't be fulfilled (objects that can't be reconciled) at that moment, because we are already at our limit.
So the crux of it comes down to the `can_take_message` closure being something like 
```rust
let next_msg_poll = scheduler
    .as_mut()
    .hold_unless(|msg| *this.is_ready_to_execute && !slots.contains_key(msg) && slots.len() < concurrent)
    .poll_next_unpin(cx);
```

again, i might be completely wrong for some obvious reason that i'm missing :)

**Comment by nightkr** [comment]
That should work, I think. One possible optimization might be to have a separate method on `Scheduler` for consuming from the queue/input but keeping _everything_ pending, which we can use to reduce work for these global conditions that don't depend on the individual objects (I'd also put `!is_ready_to_execute` in this bucket).
