### ISSUE TITLE
Client `proxy_url` handling

### ISSUE THREAD

**Issue by aviramha** [kube-rs/kube#1270]
Hi!
It seems that handling `proxy_url` in the configuration has a TODO, so it doesn't use it out of the box.
I was wondering if we can send a PR to add support to use it, instead of adding our own custom code when it happens in our source.

**Comment by aviramha** [comment]
hey @clux , would appreciate an OK from you before we work on implementing it :)

**Comment by clux** [comment]
Hey, sorry. It's been a while since looking at all this. Last I believe we left this was that the config parameter is parsed, but unused by our client builder - leaving proxying to custom clients (there are some examples). Are you looking to integrate proxy handling via the client builder somehow? I'd be interested in hearing the approach before OKing this.

**Comment by aviramha** [comment]
> Hey, sorry. It's been a while since looking at all this. Last I believe we left this was that the config parameter is parsed, but unused by our client builder - leaving proxying to custom clients (there are some examples). Are you looking to integrate proxy handling via the client builder somehow? I'd be interested in hearing the approach before OKing this.

Thanks for the response!
Yes, I want to add logic to use the given `proxy-url` by default in the client builder, I think this would be on par with Go SDK too.

**Comment by aviramha** [comment]
@clux Haven't gotten this far yet. I assume it will, and I think feature flagged is great way but I'd expect it to become default in the end

**Comment by sanmai-NL** [comment]
Just wanted to let you know that the Python Kubernetes SDK supports HTTP proxies, but not SOCKS5 proxies, even though that requires little enhancement on their side (they use the `urllib3` library, which supports SOCKS proxying). I hope you have SOCKS5 proxying in scope.
