### ISSUE TITLE
Dependency upgrades for `hyper` and `http` 1.0

### ISSUE THREAD

**Issue by clux** [kube-rs/kube#1351]
All the dependabot PRs are failing and are for now being deliberately ignored as they cannot be upgraded alone.  Unfortunately, we need to move with the ecosystem on this one, due to how tightly integrated these crates are.

TL;DR: We have to upgrade a slew of crates; `http`, `http-body`, `hyper`, all the hyper connector libs (`hyper-openssl`,  `hyper-rustls`, `hyper-socks2`, `hyper-timeout`), all the extraneous hyper libs we need to adopt because of stuff that got moved out, `tungstenite`, and `tower-http`.

- [ ] `http` - with [1.1.0](https://github.com/hyperium/http/releases) - we are on 0.2
- [ ] `http-body` - with [1.0.0](https://crates.io/crates/http-body) on crates - we are on 0.4
- [ ] `tower-http` - with [0.5.2](https://github.com/tower-rs/tower-http/releases) - we are on 0.4
- [ ] `hyper` - with [1.2.0](https://crates.io/crates/hyper) - we are on 0.14
- [ ] `hyper-openssl` - with [0.10.2](https://crates.io/crates/hyper-openssl)
- [ ] `hyper-rustls` - with [0.26.0](https://crates.io/crates/hyper-rustls) - we are on 0.24
- [ ] `hyper-socks2` - with [0.9.0](https://github.com/ark0f/hyper-socks2/pull/16) now
- [ ] `hyper-timeout` - with [0.5.1](https://github.com/hjr3/hyper-timeout/releases) - we are on 0.4
- [ ] `tokio-tungstenite` - with [0.21](https://crates.io/crates/tokio-tungstenite) - we are on 0.20 [says no real changes](https://github.com/snapview/tokio-tungstenite/blob/master/CHANGELOG.md)

`rustls` has also been making [sizeable breaking changes](https://github.com/rustls/rustls/releases) to compound the issue, but this thankfully seems __not too bad__ (comparatively) and is hopefully workable from #1418 :

- [x] `rustls` - with [0.23](https://crates.io/crates/rustls) - we are on 0.21
- [x] `rustls-pemfile` - with [2.1.1](https://github.com/rustls/pemfile/releases) - we are on 1.0

and additionally we need to grab some new utility libs spawned out of hyper/http because they didn't want to stabilise any of this:

- [ ] [hyper_util](https://docs.rs/hyper-util/l) for `client::legacy` (i think)
- [ ] [http_body_util](https://crates.io/crates/http-body-util) for new [body types](https://docs.rs/http-body-util/)

It's kind of unclear how to proceed with our `Body`: https://github.com/hyperium/http-body/issues/107
..we do have some [body extensions of our own](https://github.com/kube-rs/kube/blob/main/kube-client/src/client/body.rs#L7-L43), but hopefully that can fall away. 

There are also probably legitimate complaints with how we are doing things, but it's a big codebase, and it needs to support a lot. Help is welcome (but this is clearly difficult).

## Time Frame
I am not sure this is feasible for us to do until at least [reqwest has managed to do it's upgrade](https://github.com/seanmonstar/reqwest/issues/2039). We micic'd a lot of glue code in kube-client and if they can't even upgrade, it's less likely we can. However we could try the [backports/deprecated features](https://hyper.rs/guides/1/upgrading/) early perhaps.

## Links
- https://hyper.rs/guides/1/upgrading/
- older WIP pr at #1352 closed with [frustrated comments](https://github.com/kube-rs/kube/pull/1352#issuecomment-1939614771)
- [hyper 1.0 roadmap](https://github.com/hyperium/hyper/blob/master/docs/ROADMAP.md) with historical rationales for some of their changes
- [historical PR on hyper Body trait evolution](https://github.com/hyperium/hyper/issues/2840)
- [hyper 1.0 release](https://github.com/hyperium/hyper/releases/tag/v1.0.0)
- [reqwest WIP hyper upgrade PR](https://github.com/seanmonstar/reqwest/pull/2059/files)

**Comment by clux** [comment]
Actually kind of large number of [breaking changes from the hyper side](https://github.com/hyperium/hyper/blob/master/CHANGELOG.md#v100-2023-11-15) here actually. Trying to play around with them in #1352 to see how far we can get it towards building, but it seems to just get back normal behaviour we need to grab two new crates at the very least because:

- [`HttpConnector`](https://docs.rs/hyper/0.14.2/hyper/client/connect/struct.HttpConnector.html) is gone, and now found in a new [`hyper-util`](https://crates.io/crates/hyper-util) crate under [`::client::legacy::connect`](https://docs.rs/hyper-util/latest/hyper_util/client/legacy/connect/struct.HttpConnector.html)
- [`HttpsConnector`](https://docs.rs/hyper/0.14.2/hyper/client/connect/struct.HttpConnector.html) was moved to a new [`hyper-tls`](https://crates.io/crates/hyper-tls) crate

on top of that, [`hyper::Client`](https://docs.rs/hyper/0.14.27/hyper/client/struct.Client.html) is [gone](https://docs.rs/hyper/latest/hyper/client/conn/http1/index.html)!? and instead you only got the `Builder` with its chain-ender; [`Builder::handshake`](https://docs.rs/hyper/latest/hyper/client/conn/http1/struct.Builder.html#method.handshake) instead, and there's also a bunch of changes to `Body` which now appears to be more generic, but the [http_body](https://github.com/hyperium/http-body) crate has no changelog.

**Comment by clux** [comment]
so [`hyper::Body`](https://docs.rs/hyper/0.14.27/hyper/body/struct.Body.html) as we knew it is gone, and with it; [`body::to_bytes`](https://docs.rs/hyper/0.14.27/hyper/body/fn.to_bytes.html).

in its place is a generic [`http_body::Body`](https://docs.rs/http-body/latest/http_body/trait.Body.html) (what is re-exported from [`hyper::body::Body`](https://docs.rs/hyper/latest/hyper/body/trait.Body.html)) which is now a trait and takes two parameters; the `Data` type and the `Error` type.

i guess we try to leverage the foreign impls;
- [`impl<B: Body> Body for Request<B>`](https://docs.rs/http-body/latest/http_body/trait.Body.html#impl-Body-for-Request%3CB%3E)
- [`impl<B: Body> Body for Response<B>`](https://docs.rs/http-body/latest/http_body/trait.Body.html#impl-Body-for-Response%3CB%3E)
but there doesn't seem to be a thing for `Bytes`?

we also cannot just put the `Body<D, E>` in place of where we had it because it forces `dyn` keywords everywhere, which means we don't have `Sized`, so we have to use a boxed body, which seems to pull in [`http_body_util`](https://crates.io/crates/http_body_util) - a yet another fresh crate..

this gives us:

- [`http_body_util::combinators::BoxBody`](https://docs.rs/http-body-util/0.1.0/http_body_util/combinators/struct.BoxBody.html)
- [`http_body_util::Collected::to_bytes`](https://docs.rs/http-body-util/0.1.0/http_body_util/struct.Collected.html#method.to_bytes) (i guess we have to use a new extension trait to convert to bytes now)

..not liking this 1.0 release so far.

**Comment by clux** [comment]
ok, this is kind of hairy. the stuff i am stuck at atm is that our interfaces takes `Request<Vec<u8>>` but we need to use `Request<Incoming>` now, but `Incoming` is not something you are meant to construct yourself.

The [changelog](https://github.com/hyperium/hyper/blob/master/CHANGELOG.md) does have pointers, but you kind of have to dig into commits here and there to see, and it's such a long run-up to the release so you're never sure what's relevant and what's later been renamed on top of a removed type (e.g. hyper::Body)

The starting PR that tries to make this build is at https://github.com/kube-rs/kube/pull/1352/files and i'm going to leave it like this for at least out this month (holiday). If anyone wants to try to get this closer to building please give it a go.

**Comment by rakshith-ravi** [comment]
`hyper-rustls` has one here - https://github.com/rustls/hyper-rustls/pull/232

**Comment by allan2** [comment]
[hyper-timeout](https://github.com/hjr3/hyper-timeout) 0.5 has been released.

**Comment by rakshith-ravi** [comment]
> There's also a small [upgrading guide](https://hyper.rs/guides/1/upgrading/) now.

Yeah I went through it. Still figuring out which `body` to use for which type. I'll probably have to bring in hyper-util as well. Is that alright?

**Comment by clux** [comment]
have given up on my current branch for [reasons](https://github.com/kube-rs/kube/pull/1352#issuecomment-1939614771). going to need someone else to helm this because it's above my pain threshold to be useful :(

**Comment by rakshith-ravi** [comment]
In all honesty, it's not the end of the world, so shouldn't be the biggest issue. I'll help you out as soon as I get time, don't worry

**Comment by clux** [comment]
Have updated the root body with more up-to-date information, feel free to post any updates that could help.

**Comment by clux** [comment]
There's a working PR up for this at #1438, so this is likely to get closed soon.
