### ISSUE TITLE
Refactoring Version Dependencies

### ISSUE THREAD

**Issue by rakshith-ravi** [kube-rs/kube#1362]
Opening an issue as per the discussion on discord: https://discord.com/channels/500028886025895936/1179918831917994005

I was just going through the dependencies and I wanted to propose an alternate way to handle dependencies:
- All deps will be declared on the workspace level, with default-features = false. No deps will be declared in individual crates.
- Each individual crate can opt-in for a dependency (by just doing workspace = true.
- All versions are declared on a workspace level and will be inherited by the sub-crates.

# Motivation

This way, if we ever want to update a dependency, we have a single file (the workspace Cargo.toml file) where all the versions can be updated and all sub-crates get the same exact version. No worries about mismatch or anything else. We can even use this for path based deps. Makes things easier. This is how I do it in my repos, and they're a breeze to manage.

If that's not the direction you'd want the project to go in, that perfectly works fine too.

**Comment by clux** [comment]
This is now-done in `main` via #1435
