### ISSUE TITLE
Release Note Sketch for 0.89.0

### ISSUE THREAD

**Issue by clux** [kube-rs/kube#1441]
Lots of things in the [milestone](https://github.com/kube-rs/kube/milestone/33?closed=1) so jotting down a highlight banner for a release tomorrow. ~~Hopefully can merge [this lint + doc fix pr](https://github.com/kube-rs/kube/pull/1440) first.~~ Done.

## Upgrading `hyper` and `http` to 1.0 and MSRV to `1.75.0`
This release completes the hyper & http ecosystem upgrade #1351 via #1438. In particular, this change includes upgrades to `http`, `http-body`, `tower-http`, `hyper`, `hyper-openssl`, `hyper-rustls`, `hyper-socks2`, `hyper-timeout`, `tame-oauth`, `tokio-tungstenite`, `tower-http`, `rustls`, `rustls-pemfile`, as well as adopting the new `hyper_util` and `http_body_util` to make the change. 

While this change constitutes significant internal churn (and a new `kube::client::Body`), our external api remains largely unchanged. Some minor changes are necessary for custom clients, and for integration testing using `tower_mock`. See the [examples folder in this commit](https://github.com/kube-rs/kube/commit/aeb4d3f62052c2072ebf6fa0a88083761b0f2404) or the [controller-rs upgrade pr](https://github.com/kube-rs/controller-rs/pull/68) for details.

**Comment by aviramha** [comment]
Very exciting release!

**Comment by clux** [comment]
Closed by https://github.com/kube-rs/kube/releases/tag/0.89.0
