### ISSUE TITLE
kube::client::Body::empty() is private and cannot be used in unit tests

### ISSUE THREAD

**Issue by jeremylvln** [kube-rs/kube#1443]
### Current and expected behavior

I create a tower_test mock in some unit tests, before I could use `Body::empty()` from Hyper, but as you know it's not available anymore on Hyper v1. Fortunately, `kube::client::Body::empty()` does exists, but it's `pub(crate)` only. And the generic constructor is private.

<img width="839" alt="image" src="https://github.com/kube-rs/kube/assets/6763873/126f801c-13a5-4b39-a805-d30db8783238">

### Possible solution

Expose the `fn new()` and `fn empty()` publicly so we can use them.

### Additional context

```rust
use http::{Request, Response};
use kube::client::Body;
use kube::Client;

type ApiServerHandle = tower_test::mock::Handle<Request<Body>, Response<Body>>;
struct ApiServerVerifier(ApiServerHandle);

fn create_client_mock() -> (Client, ApiServerVerifier) {
    let (mock_service, handle) = tower_test::mock::pair::<Request<Body>, Response<Body>>();
    let mock_client = Client::new(mock_service, "default");
    (mock_client, ApiServerVerifier(handle))
}

...

send.send_response(Response::builder().status(404).body(Body::empty()).unwrap());
```

### Environment

Not relevant

### Configuration and features

```toml
kube = { version = "0.89.0", features = ["runtime", "client", "derive" ] }
```

### Affected crates

kube-client

### Would you like to work on fixing this bug?

maybe

**Comment by clux** [comment]
Ah, thanks for this. Yeah, we should expose this. Literally passed `json!({})` a few hours ago in another repo without thinking about it :facepalm:

**Comment by jeremylvln** [comment]
No worries :D

It could also be useful to update the unit test section of the docs to reflect these changes. I keep getting back to it quite often, so it might also be useful to more people

**Comment by clux** [comment]
ah yeah, i am planning on revising at least https://kube.rs/controllers/testing/ today, presumably the doc you were thinking about?
