### ISSUE TITLE
Can List support sorting?

### ISSUE THREAD

**Issue by RWDai** [kube-rs/kube#1469]
### Would you like to work on this feature?

maybe

### What problem are you trying to solve?

just like kubectl `kubectl get pods --sort-by=.status.startTime` have sort param

### Describe the solution you'd like

add sort in `ListParams`

### Describe alternatives you've considered

If it doesn't work, just sort it manually based on meta.

**Comment by clux** [comment]
unfortunately that is a client-side sort done by kubectl after receiving it from the apiserver in https://github.com/kubernetes/kubectl/blob/master/pkg/cmd/get/sorter.go

you can replicate in rust by collecting an `api.list` result into a `Vec` and using one of the many sort methods available:

```rust
        let mut pvec = pods.into_iter().collect::<Vec<Pod>>();
        pvec.sort_by_key(|p| {
            p.metadata
                .as_ref()
                .unwrap()
                .creation_timestamp
                .as_ref()
                .unwrap()
                .0
        });
```

from an [ancient piece of code](https://github.com/clux/shipcat/blob/master/shipcat_cli/src/status.rs#L102-L111) but should work

**Comment by RWDai** [comment]
ok,thank you. If the sorting is not done by apiserver, then there is really no need for kube to implement this function.
