### ISSUE TITLE
Breaking api changes between minor versions of json-patch dependency

### ISSUE THREAD

**Issue by avtrujillo** [kube-rs/kube#1486]
### Current and expected behavior

Code that previously compiled successfully started failing with multiple errors similar to

> 281.0    --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/kube-runtime-0.90.0/src/finalizer.rs:141:31
> 281.0     |
> 281.0 141 |                         path: finalizer_path.clone(),
> 281.0     |                               ^^^^^^^^^^^^^^^^^^^^^^ expected `Pointer`, found `String`

without any change to the version of my kube dependency. After some digging, I found that json-patch made breaking api changes between[ v1.2.0 and v1.3.0](https://github.com/idubrov/json-patch/compare/v1.2.0...v1.3.0), which replaced several uses of String with jsonptr's Pointer in the public fields of several public structs used by kube, including RemoveOperation, MoveOperation, PatchOperation, CopyOperation, ReplaceOperation and AddOperation.

### Possible solution

Set json-patch "= 1.2.0" in Cargo.toml as a temporary solution, or bump the json-patch version and  replace usage of String with jsonptr's Pointer type where appropriate.

### Environment

Client Version: v1.26.15-dispatcher
Kustomize Version: v4.5.7
Server Version: v1.27.11-gke.1062001

Dockerfile OS: rust-1.77.2-slim-bookworm

### Affected crates

kube-runtime

### Would you like to work on fixing this bug?

maybe

**Comment by pgerber** [comment]
Upstream report: https://github.com/idubrov/json-patch/issues/39

**Comment by clux** [comment]
Thanks for the report. This has had not hit any renovate cycles for myself yet. It looks like it's yanked and reverted in a new 1.4.0 release of `json-patch` so hopefully this should not affect any new CI runs for people.

**Comment by clux** [comment]
Closing as fixed upstream.
