### ISSUE TITLE
Release 0.92

### ISSUE THREAD

**Issue by clux** [kube-rs/kube#1513]
lots of proxy and watcher stuff in the [milestone](https://github.com/kube-rs/kube/pulls?q=is%3Apr+milestone%3A0.92.0+is%3Aclosed) and it's in a good state atm (no big follow-ups planned on my end in stable), but have plans for unstable stuff in stream sharing. shouldn't let that block a release though.

jotting down some provisional highlights (will edit in links/callouts later as appropriate).

## Runtime: Decreased Memory Usage from `watcher`
Buffering of [initial pages](https://kubernetes.io/docs/reference/using-api/api-concepts/#retrieving-large-results-sets-in-chunks) / [init streams](https://kubernetes.io/docs/reference/using-api/api-concepts/#streaming-lists) is no longer a mandatory process with `watcher::Event` gaining new `Init`, `InitApply`, and `InitDone` events. These events are read on the [store side](https://github.com/kube-rs/kube/blob/main/kube-runtime/src/reflector/store.rs#L99-L134) maintaining the atomicity/readiness guarantees for `reflector` and `Store` users.

This should provide a significant memory decrease for `watcher` users (both with and without stores). See https://github.com/kube-rs/kube/pull/1494 for benchmarks.

The downside is a **breaking change** to `watcher::Event`. Plain usage of `watcher` / `reflector` / `Controller` should generally not need to change anything, but custom stores / matches on `watcher::Event` will need an update. If you are writing custom stores, the new signals should be helpful for improved caching.

Thanks to `@fabriziosestito` via [Kubewarden](https://www.kubewarden.io/) for https://github.com/kube-rs/kube/pull/1494 . Follow-ups for this feature: https://github.com/kube-rs/kube/pull/1499 and https://github.com/kube-rs/kube/pull/1504.

## Client: HTTP Proxy Support
Support is now introduced under the `http-proxy` [feature](https://kube.rs/features) pulling in [hyper-http-proxy](https://crates.io/crates/hyper-http-proxy) complementing the already existing `socks5` proxy feature.

Thanks to `@aviramha` via [MetalBear](https://metalbear.co/) for the support in https://github.com/kube-rs/kube/pull/1496, with follow-ups https://github.com/kube-rs/kube/pull/1501 + https://github.com/kube-rs/kube/pull/1502

**Comment by aviramha** [comment]
Thanks @clux  for the great release and @Razz4780 for the initial HTTP Proxy Support implementation!

**Comment by clux** [comment]
Thanks for all the help. Closed as released; https://github.com/kube-rs/kube/releases/tag/0.92.0
