### ISSUE TITLE
Add ability to add headers to the client

### ISSUE THREAD

**Issue by aviramha** [kube-rs/kube#1521]
### Would you like to work on this feature?

yes

### What problem are you trying to solve?

When using mirrord cli to communicate with the cluster, we'd like to send our custom headers with every Kube interaction (As usually it's being handled by our operator).
Currently we add the needed headers to specific [requests](https://github.com/metalbear-co/mirrord/blob/52783b405fdbcc02f9f733f08f85b1009c0b3792/mirrord/operator/src/client.rs#L511)

### Describe the solution you'd like

I'd like to be able to add headers in a concise manner (without doing a lot of boilerplate/implementing structs)
Some options I thought about:

1. Add new field to `Config` of `Vec<Headers>` that will be appended as part of `extra_headers_layer`.
2. Add a new method to ClientBuilder that adds the headers as a layer
I prefer 1 because it would be easiest in terms of API/change (if we do it in ClientBuilder then we add a new layer while we already have a layer for static headers..)

### Describe alternatives you've considered

Building our own stack and adding layers.

### Target crate for feature

kube-client

**Comment by clux** [comment]
I think this makes sense. I don't see any other way to pass extra header information in the [upstream kubeconfig struct](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/tools/clientcmd/api/types.go) so it makes sense to have this a rust only override in `Config` - and hooking it into `ConfigExt::extra_headers_layer` seems pretty nice.

**Comment by aviramha** [comment]
Thanks for the feedback @clux. Looks like easy implementation so there's a PR now :)
