### ISSUE TITLE
Unsupported kind of private key

### ISSUE THREAD

**Issue by aviramha** [kube-rs/kube#1536]
### Current and expected behavior

`kubectl get pods` works in a cluster where a kube-rs based client doesn't.
Since it's a private key user can't share it - let me know if more info we can gather to debug it
`openssl pkey -in /tmp/aaaa.key -text -noout` output
Private-Key: (2048 bit, 2 primes)
modulus:
    REDACTED
publicExponent: 65537 (0x10001)
privateExponent:
    REDACTED
prime1:
    REDACTED
prime2:
    REDACTED
exponent1:
    REDACTED
exponent2:
    REDACTED
coefficient:
    REDACTED

### Environment

KubeSphere  v3.3.0-rc.3
Kubernetes   v1.22.10

### Affected crates

kube-client

### Would you like to work on fixing this bug?

Yes
https://github.com/metalbear-co/mirrord/issues/2578

**Comment by aviramha** [comment]
I assume this is an issue upstream on rustls

**Comment by clux** [comment]
I assume it is, but just a FYI that we don't do anything for aws_lc atm we have it explicitly disabled for build reasons - not sure if we need to do anything to support it.

(saw your post referencing it https://github.com/rustls/rustls/issues/2038#issuecomment-2214171955 )

**Comment by aviramha** [comment]
https://github.com/rustls/rustls/issues/2038#issuecomment-2216832304
