### ISSUE TITLE
`Api::get("")`  (get with empty name), will send a command to the k8s-api-server that looks like a `list` and thus will result in a serde error.

### ISSUE THREAD

**Issue by xMAC94x** [kube-rs/kube#1540]
### Current and expected behavior

When callind `Api::get()` with a `name:&str` which is `""` kube will generate an Api call to the k8s server which is equal to the list call (prob because the trailing / is ignored here https://github.com/kube-rs/kube/blob/0.92.1/kube-core/src/request.rs#L84 .
The ApiServer will send a List, e.g. `PodList` (or whatever) back instead a single instance.
As a result serde will always fail here https://github.com/kube-rs/kube/blob/0.92.1/kube-client/src/client/mod.rs#L249

while we could argue that the behavior from `kube` side is completely valid, it is a bit inconvenient and makes debugging a tiny bit harder.

as an empty string is probably a invalid name for a Kubernetes ressource (needs to be verified), we can fail early on and don't need to do the actually request, especially dont fail with that serde error. For performance reason maybe only in debug mode.

If you tell me where to make the change I can also provide an PR. (In case this bug is valid for you at all)

### Possible solution

Check `&name` within `Api::get()` and return an error, maybe here:
https://github.com/kube-rs/kube/blob/0.92.1/kube-core/src/request.rs#L83
and return
`Error::Validation`

### Environment

AWS cluster:
Server Version: v1.30.2-eks-db838b0

should be independent of this though

### Configuration and features

```toml
kube = { version = "0.92", features = ["runtime", "client", "derive"] }
k8s-openapi = { version = "0.22", features = ["v1_30"] }
```

### Affected crates

kube-core, kube-client

### Would you like to work on fixing this bug?

yes

**Comment by clux** [comment]
Thanks for the report. I agree we should fail early on this. 

I imagine this should be handled using the `Error::Validation` variant exposed in kube-core/../request.rs. This variant commonly brings up user errors and is typically passed up early. We could probably return it in all the `get_` functions implemented on `Request` in request.rs (which I assume will error similarly).

**Comment by xMAC94x** [comment]
I am working on a PR,
Interesting notes:
 - there is no exhaustive list of constrains for names, https://kubernetes.io/docs/concepts/overview/working-with-objects/names/ just mentions four common  constrains. They don't mention any minimum-length, though all 4 common types require to start with a alphanumeric character (implicitly making it at least 1). It mentions that some are stricter, but there is no mentioning of less strict constrains.
 - go had a similar issue, fixed in a similar way: https://github.com/kubernetes/kubernetes/pull/75072/files
  - Go mentions `Delete`, `Get` and `Patch` calls, I will do some local tests and implements ours accordingly. We need to check how the empty URL path_segment is interpreted by API server, we prob don't want to replace all instances with a single one or delete all `x` because we accidentally used an empty name.
