### ISSUE TITLE
A way to aggregate repeated events with the recorder.

### ISSUE THREAD

**Issue by johnthompson-ybor** [kube-rs/kube#1606]
### Would you like to work on this feature?

None

### What problem are you trying to solve?

As far as I can tell, there's only a way to create new events which all get displayed separately -- I need a way to aggregate events that happen more than once within a certain amount of time.  The go recorder does this:

https://pkg.go.dev/k8s.io/client-go/tools/record#EventAggregator

### Describe the solution you'd like

Some way to update the count of an existing event or otherwise aggregate events.

### Describe alternatives you've considered

using the events api directly instead of the recorder.

### Target crate for feature

kube-runtime

**Comment by clux** [comment]
That seems to be a different way of doing something we already do in the `Controller`; debouncing repeat events to the same object. 

Have a look at [controller docs for debouncing](https://kube.rs/controllers/optimization/#debouncing-repetitions), maybe this is sufficient for yoou?

**Comment by johnthompson-ybor** [comment]
That's for events you're subscribed to -- i'm talking about publishing events -- see this from client go:

https://github.com/kubernetes/kubernetes/blob/9568a2ac145cf9be930e3da835f86c1e61f7f7c1/staging/src/k8s.io/client-go/tools/record/events_cache.go

**Comment by johnthompson-ybor** [comment]
It's quite possible I'm misunderstanding how this works, but the main issue is if i'm publishing the _exact same event_ multiple times with the kube-rs recorder, it doesn't get aggregated in kubernetes, it shows up as distinct events.

**Comment by clux** [comment]
Oh, I see, apologies. Indeed, we do not have any way of doing this.

This does sound like nice functionality/module to have, but would need some time to sit down with this to see how it could be adopted in a sane rust-idiomatic way. Experiments/comments/direction advice here are definitely welcome.
