### ISSUE TITLE
Add "disable-compression" to selectively disable Client Compression

### ISSUE THREAD

**Issue by markdingram** [kube-rs/kube#1627]
### Would you like to work on this feature?

yes

### What problem are you trying to solve?

Currently compression is tied to the `gzip` feature. The use case for bringing in the [disable-compression](https://kubernetes.io/docs/reference/config-api/kubeconfig.v1/) config option is to facilitate a gradual rollout across many clusters without needing 2 binaries.

Previously discussed here:
https://github.com/kube-rs/kube/pull/1331#discussion_r1381627808

### Describe the solution you'd like

Add the "disable-compression" flag & flow through to the Client construction to allow selective disable even when `gzip` feature is enabled

### Describe alternatives you've considered

None

### Target crate for feature

kube-client

**Comment by clux** [comment]
Seems reasonable to me. Can be defaulted sensibly, and can be documented as 'only has an effect when gzip feature is enabled'.
