### ISSUE TITLE
Increase flexibility on store public API

### ISSUE THREAD

**Issue by pando85** [kube-rs/kube#1633]
### Would you like to work on this feature?

None

### What problem are you trying to solve?

I would like to get a list of objects filtered by a function from a store. I found that just [the find method](https://github.com/kube-rs/kube/blob/9c402a6825e4ca966f74d3d38a65af2d487b6dec/kube-runtime/src/reflector/store.rs#L248) could be similar to my needs. With this method

I can retrieve one item per controller reconcile which is good enough but it could be better.

### Describe the solution you'd like

Expose the `store` attribute or any interface that gives you more flexibility.

### Describe alternatives you've considered

- call the API each time that I need to get those items: more inefficient and complex. Also really don't need it.
- do nothing. Good enough behavior for my use case.

### Target crate for feature

kube-runtime

**Comment by clux** [comment]
If I am reading it correctly, you are after some kind of `find_slice` / `find_all` method. I think this is a reaonsable thing to add also.

**Comment by pando85** [comment]
Yes, I expect to get all the elements filtered by some condition.

How, in your opinion, is the best way to proceed here? I could add the code.

**Comment by clux** [comment]
Do feel free to add it! Imagine a `find_all` returning a slice of `Arc<K>` (or a `Vec<Arc<K>>` if that's cumbersome) should be easy to review.

**Comment by pando85** [comment]
I didn't realize that I can use the `state` method from store and get an iterator from the values.

I will close it.
