### ISSUE TITLE
add support for Azure oidc auth

### ISSUE THREAD

**Issue by clux** [kube-rs/kube#501]
~~Azure auth provider was working before we refactored it (as we fixed #238), but it was always shoehorned into the `load_gcp` fn at the time. Now it's done better, but~~ looks like people are having issues now: https://github.com/Dentrax/kubesql/issues/1
Edit: This probably never worked.

The source for the azure auth can be found in https://github.com/kubernetes/client-go/tree/master/plugin/pkg/client/auth/azure in client-go.

Support for this should probably exist elsewhere than in kube, like in `tame-oauth` (which we use for the gcp flow) is [open to supporting other flows](https://github.com/EmbarkStudios/tame-oauth#why-not).

~~We need a handler in [token_from_provider](https://github.com/clux/kube-rs/blob/9ce641324494fe6517e4114ba831793f48eed5a0/kube/src/service/auth/mod.rs#L175). It's even possible that the `token_from_gcp_provider` one even works, but we had quite a bit of changes to simplify our oauth stuff by using tame_oauth, so not sure if that's true anymore.~~

~~Similar PR: https://github.com/clux/kube-rs/pull/419/files~~

**Comment by bocc** [comment]
Sorry for asking here, but do you have any updates on this one? I'd like to authenticate with Azure, but I have no leads currently.

**Comment by kazk** [comment]
Similar to GCP OAuth, it's now [deprecated](https://github.com/kubernetes/kubernetes/blob/bbc3a9aace18ae40598e5279202cc67a89d7b9f3/staging/src/k8s.io/client-go/plugin/pkg/client/auth/azure/azure.go#L90-L95):

```go
	// deprecated in v1.22, remove in v1.25
	// this should be updated to use klog.Warningf in v1.24 to more actively warn consumers
	warnOnce.Do(func() {
		klog.V(1).Infof(`WARNING: the azure auth plugin is deprecated in v1.22+, unavailable in v1.25+; use https://github.com/Azure/kubelogin instead.
To learn more, consult https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins`)
	})

```

Replaced by [kubelogin](https://github.com/Azure/kubelogin), which is an exec plugin, so that should be supported. Please open an issue if that doesn't work.

If you really need OAuth support, I'd recommend working with `tame-oauth` to add Azure support first.

**Comment by bocc** [comment]
Thank you for pointing this out! `kubelogin convert-kubeconfig` did the trick.
