### ISSUE TITLE
resolver 1 fallback does not work in edition 2021

### ISSUE THREAD

**Issue by clux** [kube-rs/kube#665]
Trying to figure out why this is. Have tried setting `resolver = "1"` to get the old behaviour, but getting the `k8s-openapi` compile time failure when publishing.

might open a bug upstream :thinking:

**Comment by webern** [comment]
I may be hitting this with a local cargo install command:

```shell
cargo install --path "${MY_WORKSPACE}/mything" --features k8s-openapi/v1_20 --force
``

I don't understand why I didn't see this before, it seems like it just popped up and I'm not sure if it's the same problem. Changing my command to specify features does not fix the problem:

```shell
cargo install --path "${MY_WORKSPACE}/mything" --features k8s-openapi/v1_20 --force
```

I do have this in the Cargo.toml for this binary

```
[dependencies]
# ...
k8s-openapi = { version = "0", features = ["v1_20", "api"], default-features = false }
```

**Comment by clux** [comment]
this is likely because there's a new version of k8s-openapi and the kube release picking up on it has not been released yet. hang on, will release the new kube version.

**Comment by clux** [comment]
kube 0.67 is out now, I expect that should resolve the issue

**Comment by webern** [comment]
I don't think that was the issue, I'm using an older version right now anyway, 0.64 / 0.13.1 (I will update soon but that's in another PR waiting to let some PRs settle before merging).

I tried changing my Cargo.toml to say (though this is what's already in my workspace's Cargo.lock):


```
k8s-openapi = { version = "=0.13.1", features = ["v1_20", "api"], default-features = false }
kube = { version = "=0.64.0", default-features = true, features = ["config", "derive", "ws"] }
```

I did a cargo clean and then cargo install --path "${MY_WORKSPACE}/mything" --force

This time I got the type of error that indicates there are two versions of a struct or trait:

```
error[E0308]: mismatched types
   --> model/src/system/controller.rs:185:32
    |
185 |                   metadata: Some(ObjectMeta {
    |  ________________________________^
186 | |                     labels: Some(btreemap! {
187 | |                         LABEL_COMPONENT.to_string() => "controller".to_string(),
188 | |                     }),
189 | |                     namespace: Some(NAMESPACE.to_string()),
190 | |                     ..Default::default()
191 | |                 }),
    | |_________________^ expected struct `k8s_openapi::apimachinery::pkg::apis::meta::v1::ObjectMeta`, found struct `kube::kube_core::ObjectMeta`
    |

```

I definitely don't understand what's going on. I'll continue trying to figure it out tomorrow.

**Comment by clux** [comment]
Well, that still looks like a multiple versions issue because `k8s_openapi::apimachinery::pkg::apis::meta::v1::ObjectMeta` is what we re-export as ObjectMeta.

Maybe try `cargo tree | grep k8s-openapi` to verify that you only have one version of it present.

**Comment by webern** [comment]
Thank you for your help with is. It was ultimately a version mismatch stemming from my belief that version = "0" would choose the correct "major" version of k8s-openapi. That doesn't seem to be the case, so I'll make sure to specify 0.X.
