### ISSUE TITLE
`doc_cfg` hints attached to re-exported items are not shown

### ISSUE THREAD

**Issue by kazk** [kube-rs/kube#715]
https://docs.rs/kube/ only shows `doc_cfg` hints from `kube` because of known bugs:

- https://github.com/rust-lang/rust/issues/83428
- https://github.com/rust-lang/rust/issues/88743

Maybe we should add notes like `/// Required features: ws`

**Comment by kazk** [comment]
See #1242

**Comment by clux** [comment]
Ah, whoops. Didn't see this one.
