### ISSUE TITLE
Watcher breaks if any object cannot be deserialized

### ISSUE THREAD

**Issue by nightkr** [kube-rs/kube#774]
### Current and expected behavior

Let's say that we define the CRD spec as follows (this is just illustrative of the problem, I haven't tried compiling this...):

```rust
#[derive(CustomResource)]
#[kube(group = "dinner.com", version = "v1alpha1", kind = "Food")]
pub struct FoodSpec {
    price: i8,
}
```

And apply the generated CRD, as well as two objects of the specified type:

```yaml
apiVersion: dinner.com/v1alpha1
kind: Food
metadata:
  name: eggs
spec:
  price: 10
---
apiVersion: dinner.com/v1alpha1
kind: Food
metadata:
  name: spam
spec:
  price: -5
```

So far, everything works fine and our watcher reports the object just fine.

However, eventually some smartass decides that negative prices don't make sense, and changes the `FoodSpec` definition:

```rust
#[derive(CustomResource)]
#[kube(group = "dinner.com", version = "v1alpha1", kind = "Food")]
pub struct FoodSpec {
    price: u8,
}
```

Now we have some orphaned objects that would no longer validate, but which have effectively been grandfathered in. `watcher` sees the error and fails immediately, swallowing all objects if `eggs` could have been parsed just fine. This percolates down the ecosystem, and causes `Controller` to fail in the same way.

### Possible solution

I'm not sure. Maybe we `watcher` should return some kind of `Result<K, Undeserializable>`? Then again, that would probably hurt ergonomics quite a bit... How should `reflector` handle this case? We might also want to split between "object is A-OK", "metadata is OK, but the rest is unreadable", and "zalgō̸̰ c̴͖̒ö̷̰́mes for us a̶̡̓ll".

This will probably also need to change in `Api::list` and `Api::watch` somehow...

### Environment

This is a client issue.

### Affected crates

kube-client, kube-runtime

### Would you like to work on fixing this bug?

yes

**Comment by teozkr** [comment]
Agreed that we need that too, and that creating a new version is the correct way to deal with this kind of breakage.
