### ISSUE TITLE
Support k3s/k3d out of the box with rustls-tls

### ISSUE THREAD

**Issue by farcaller** [kube-rs/kube#805]
### Would you like to work on this feature?

yes

### What problem are you trying to solve?

The default k3s config uses Sec1-enocoded ec private keys and points at https://127.0.0.1:6443

### Describe the solution you'd like

kube-rs works with the default unmodified kubeconfig.

### Describe alternatives you've considered

modifying the kubeconfig so it uses pkcs#8-wrapped private keys/localhost.

### Documentation, Adoption, Migration Strategy

This is a tracking bug for features that need to be landed downstream for kube-client to work:
- [x] https://github.com/kube-rs/kube-rs/pull/804
- [ ] https://github.com/briansmith/webpki/issues/54

### Target crate for feature

kube-client

**Comment by clux** [comment]
The second part of this issue should now be resolved also thanks to the rustls-webpki fork which ultimately closed #153.
Thus, rustls should work out of the box with k3d from 0.81.0
