### ISSUE TITLE
kube facade crate doesn't depend on exact versions of the backing crates

### ISSUE THREAD

**Issue by nightkr** [kube-rs/kube#833]
### Current and expected behavior

`kube` 0.69.1 currently depends on version `^0.69.0` of the  subcrates, meaning that any 0.69.x version is acceptable. This means that even users who upgrade to kube 0.69.1 maybe end up using the broken kube-client 0.69.0 until they run a `cargo update`.

This also breaks minor downgrades, which would still end up using the latest versions of the backing crates.

Instead, crates should use exact dependencies (such as `=0.69.1`) for sibling dependencies.

### Environment

Irrelevant, this is a Cargo packaging issue.

### Affected crates

kube-core, kube-client, kube-derive, kube-runtime

### Would you like to work on fixing this bug?

yes

**Comment by clux** [comment]
yeah, this is wrong. agree we should change pin in `dependencies` field and make it exact.

NB: as long as we don't touch `dev-dependencies` case. dev-deps kube dep is an open ended-range for testing as dev-deps have cyclical deps locally.
