### ISSUE TITLE
Admission Controller example will delete any existing labels

### ISSUE THREAD

**Issue by Alibirb** [kube-rs/kube#943]
### Current and expected behavior

The admission controller example adds a json patch to add the `/metadata/labels` field in case it doesn't exist. If the `labels` field already exists, this seems to re-create the field, empty, so all existing labels are lost. Since labels are often used to keep track of objects (e.g. `ReplicaSet` uses it to tell which `Pods` it created), this can have disastrous effects (e.g. the `ReplicaSet` thinks the pods keep dying, so it infinitely spawns new Pods).

### Possible solution

Check if the `/metadata/labels` field already exists, and only create it if it doesn't already exist.

### Environment

```
$ kubectl version --short
Client Version: v1.20.5
Server Version: v1.23.3
```

### Would you like to work on fixing this bug?

yes

**Comment by teozkr** [comment]
Oof, that's not great!

**Comment by clux** [comment]
Ah, good find, thank you. Yeah, a PR for this would be very much appreciated if you have time!
