### ISSUE TITLE
serde_yaml 0.9

### ISSUE THREAD

**Issue by nightkr** [kube-rs/kube#980]
serde_yaml 0.9.x now generates documents that are inconsistent with what `kubectl` (and the rest of the K8s ecosystem) expects (as well as the schemas generated by `schemars`), see https://github.com/stackabletech/operator-rs/pull/450, https://github.com/dtolnay/serde-yaml/issues/298.

We probably need to figure out a decent strategy for handling this on our end, and discourage use of 0.9 until we have a proper answer.

**Comment by clux** [comment]
Looking at the issues for this and seeing how both stackable and the example controllers have upgraded to serde_yaml 0.9 I don't think there's a particular need for us to hold back here anymore.

Our usage of serde_yaml is generally only for tests (it's a dev dep in kube-core + kube-derive) with only one legit use case (config loading) from kube-client.
